
<DemoButton@Button>:
  size_hint: (1.0, 1.0)
  background_color: (1.0, 0, 0, 0.8)
  count: 0
  text: 'Click'
  
  on_press:
    self.count += 1
    self.background_color = (1.0, self.count/10.0, 0, 0.8)
    self.text = '{}'.format(self.count)

<SquareDemoButton@DemoButton>:
  # Text size is for wrapping text etc.
  # text_size: self.height, self.height
  text: 'X'
  font_size: self.height
  size_hint: None, 1.0
  size: self.height, self.height
      
